# Generated by Django 3.2.13 on 2023-02-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('lat', models.TextField()),
                ('lon', models.TextField()),
                ('items', models.TextField()),
                ('detail', models.TextField()),
                ('stadium', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Stadium_stores', to='articles.stadium')),
            ],
        ),
    ]
