# Generated by Django 3.2.13 on 2023-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
