# Generated by Django 3.2.13 on 2023-03-08 14:28

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_image', to='foods.store')),
            ],
        ),
    ]
