# Generated by Django 3.2.13 on 2023-02-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('foods', '0003_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='team',
        ),
        migrations.AddField(
            model_name='store',
            name='stadium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Stadium_stores', to='articles.stadium'),
        ),
    ]
